AaltoSciComp/python-for-scicomp

index.rst
- To review: good to read all things, but iterations will continue so
it doesn't need to be perfect yet.
=> index: Rearrange the index

jupyter.rst
- This is a first draft of Jupyter exercises: the minimum I think we
need in order to get through the course.
- First draft only, I haven't given these too much thought overall.
- To review:
- Do they generally make sense?
- I would like to add a few conceptual exercises.
- I worry this is too long, we have currently planned 30 minutes for
Jupyter.  Since this is the very start, it's going to be slow
going getting started...
- Do we instead want to start with one of the CodeRefinery examples
to make it concrete.  Hm, yes, we should probably do that...
=> jupyter: Add jupyter exercises

binder.rst
2 exercises:
- First exercise is a discussion about the need to share more than source code e.g. share computational environment.
- Second exercise is to binderize an existing repository, adding `requirements.txt`
=> drafted exercises for binder

index.rst, installation.rst
- Copied from existing instructions, but heavily revised.
- Recommend only anaconda as the tool of choice.
- Also point to some other tools, such as text editor, git, etc.
These are not as important so perhaps they could be de-empahasized,
but if learners don't have these then they will get stuck with some
parts.  I haven't thought too much to make sure I considered all the
cases here... revisions welcome.
- For the most part, link to CodeRefinery installation instructions
(which mostly apply here).
- Review:
- Is the content good?  Is it mostly correct and what we want?
- I am sure there is still room for minor fixups, this is just a
first pass.
=> installation: Add installation instructions in a new page

matplotlib.rst
Just fixing a small missing "np."
=> Missing np. at the beginning

numpy.rst
Fixed a missing space and suggested a change for linspace.
Is Exercise 2.5 too demanding or did you budget it in the time needed?
Still missing: questions/objectives/keypoints
=> Fixed a missing space and suggested a change

installation.rst
- If someone can start JupyterLab, that is all they need (since it
includes the terminal).  Rearrange instructions to emphasize
jupyterlab-first.
- Review: general check + details
=> installation: Add jupyter video, clarify installation some.

index.rst
- So that they are both linked to each other.
=> index: Add link to course page

installation.rst
Maybe a bit late and not sure if necessary but I found the installation instructions to be a bit confusing especially if someone has never worked with the software. Tried to clean up a bit and added a list of software to install ( complete) also with python libraries. Please review :)
=> adding list of software

binder.rst
- For discussion, see #32
- Closes: #32
=> binder: Fix multiple target warnings

data-visualization.rst, index.rst
i want this to be more general than just about a specific library
since i will also point to other libraries.
the episode content will mostly be about matplotlib but one
could imagine this to become more general in future
=> rename "matplotlib" to "data visualization with matplotlib"

.gitignore, numpy.rst, numpy_old.rst
Moi, please all take a look and either comment for me to implement or feel also free to push directly :)
=> numpy lesson drafted, please take a look

scripts.rst
=> reduce heading levels to avoid separate sections, fixes #45

numpy.rst
fixing typos we found during run-trough and one solution block
=> fixing small typos

numpy.rst
=> cosmetic changes and a missing parenthesis

numpy.rst
Adding solutions for the "Addittional Exercises", there could be more text with explanations + links to NumPy documentation.
=> Adding solutions for the NumPy "Addittional Exercises"

numpy.rst
- Changed as discussed earlier today, but seems to miss the reshape.
- Review: @samumantha
=> numpy: reshape 4x4 array

packaging.rst
follow-up work will be organized in smaller size issues
@annefou can you take a look whether this makes sense?
=> more ideas for "packaging" episode; closes #7

index.rst
move dependencies episode before packaging
=> swap episode dependencies fix #72

dependencies.rst
Most tried to set learning objectives. very rough draft of the episodes (some headlines but it needs some rework).
=> Dependencies

installation.rst
- Works on Windows and Linux at least
=> installation: Add anaconda navigator for command line

scripts.rst
Problem was raised in issue #6
=> move jupytext to end of episode scripts

dependencies.rst
(i don't think we will get to this section but nice to have for
later)
=> add examples to version pinning; closes #80

data-visualization.rst
add links to other popular plotting packages.
=> additional link for popular plotting packages

dependencies.rst
i often use the former version but i think the -m venv
is "better"/recommended?
=> is this better?

dependencies.rst
some text/intro is missing in front of the exercise but i will add that
=> work on recording dependencies; closes #82

scripts.rst
=> scripts: minor syntactic revisions

dependencies.rst
- Minor revisions to dependencies
- Review: does CI pass?
=> dependencies: minor revisions

dependencies.rst
- https://scicomp.aalto.fi/scicomp/packaging-software/
- I wrote it so I'm a bit biased, but I think it is a good intro to
basics
- Review: is this suitable for a "see also" ?
=> dependencies: Link to Aalto "packaging guidelines"

numpy.rst
- Thanks to @eglerean for the link to the nature paper
- Also move keypoints to very bottom
- Review: minimal needed
- But are there these good numpy pages to highlight?
=> numpy: add See Also section

libraries.rst
- I've divided the scipy ecosystem into sections and put some of the
main packages there.  Perhaps even too many packages, but it's some
sort of starting point.
- Review: check if it's on a good track, and are there generally too
many or two few things.  But, it can be merged quickly and iterated
=> libraries: Add initial outline

index.rst
=> arrange lessons to the order how we will give them

parallel.rst
to be turned into a demo and text to be added
=> mpi4py example

parallel.rst
- Draft, but key concepts including an exercise are there.
Multiprocessing is not yet explained but the major exercise is
there.
- Review: general, but also can be merged and iterated later.
=> parallel: Add introduction through multiprocessing draft

binder.rst
and add timing to exercises; exercise to upload a repo in zenodo is made optional (do not work ahen using sandbox) so better to skip it
=> clarify binder episode

conf.py, parallel-pi-multiprocessing.ipynb, parallel.rst
- Add multiprocessing explanation + solution
- Enable intersphinx
- Review: It's worth looking details now.
=> parallel: refine the multiprocessing example more

scipy.rst
- Update text, add some structure.
- Add solution to one exercise (one still without).  These exerercises
aren't intended to be done, but considered examples.
- This could almost be considered done by now.
- Review: general, can iterate later
=> scipy: General update

parallel.rst
more changes coming in separate PRs
=> parallel programming: reworded few sentences

parallel.rst
no exercise here, is a bit too advanced in my opinion
but if time permits we can discuss and show some examples
=> text for "Coupling to other languages"

pandas.rst
where it fits together with the topic "learning a new package"
=> move callout box on getting help to top

parallel.rst
i already had a bad feeling about returning the input variable
again :-)
=> bugfix for mpi example

libraries.rst
- Finish the episode
- Review: minimal needed
=> libraries: Add links and finalize

content/index.rst
- Make it sound like python3 is default in most cases except
unmaintained software.
- Warn people of incompatibility.
- Review: quick read
=> content/index: Update statement about python 2

content/installation.rst
- Review: automerge based on chat
=> content/installation: Remove warning, good to go

content/libraries.rst
- This is a major refactor of the libraries lesson, based on bad
feedback from last year.
- It clarifies two goals:
- Know that other mainstream packages exist and you can find most of
what you need.  The concept of dependencies.
- You will often need to use smaller packages which you find
scattered around.  How to evaluate these (and inspiration to )
- I think this is better, but will still need lots of revisions,
reducing text, and filling in some missing spots.
- Review:
- General read and advice
- I would recommend merging already, and then review via further
updates after reading the renderede text.
=> content/libraries: Major refactor

content/installation.rst
- Note that miniconda doesn't provide Anaconda Navigator and thus you
need to do the command line.
- Note about miniconda activation
- A few links in a "see also" section
- Review: quick read or automerge
=> content/installation: miniconda warnings/activation, see also

content/data-formats.rst
- Not everything, since these links are a bit involved...
=> content/data-formats: Some intersphinxing of data-formats

content/jupyter.ipynb
x for cut, c for copy, d,d for delete cell
=> Jupyter shortcuts

content/index.rst
As requested by some learner, I have added a link to short course on basic python syntax
=> Added a link to short course on basic python syntax

content/scripts.rst, resources/code/scripts/weather_observations.py, resources/code/scripts/weather_observations_argparse.py, resources/code/scripts/weather_observations_config.py
Removing function packaging (the packaging section gives some hints here), and focusing more on making scripts flexible (i.e. arg-parsing). 
Sys.env just as a demo and argparse then as an actual exercise. Also updated the corresponding scripts.
=> Updating Scripts

content/dependencies.rst
These commits add:
- More information on the difference of pip and conda
- Add quick overview of conda ecosystem
- Make example environments buildable from defaults, conda-forge and pip
- Add warning on problems that might arise when building environments manually
- Bit more information on the environments chapter about the difference of requirements.txt and environment.yml
=> Dependency 2022

content/numpy-advanced.rst
These are things that came up during our first run-through of the lesson.
Some fixes to the code examples. Moved the `transpose()` example up a bit.
=> Some tweaks to the Advanced Numpy lesson

content/data-formats.rst, content/format_comparison_array.csv, content/format_comparison_tidy.csv, extras/data-formats-comparison-array.ipynb, extras/data-formats-comparison-tidy.ipynb
Major rewrite:
- Reorganize exercises throughout the text.
- Make exercises a bit easier and less reliant on external libraries.
- Organize tidy data and array data formats into their own chapters.
- Change format advantage / disadvantage descriptions to easier to grasp colors (green, yellow, red).
- Add information on other formats (graph formats, sparse matrices).
- Format benchmarks into csv tables.
=> Data formats 2022

content/web-apis.ipynb
Fix typos and clean up the Web API session notebook.
=> Fix typos and clean up excluded code

content/data-formats.rst
- I think the symbols could still be improved but this is the most
urgent fix
=> content/data-formats: Make red/green/blue emojis more color-blind friendly

content/data-formats.rst
This PR changes the yellow circle icon to yellow square that more closely matches the other icons. It also fixes a typo in the JSON example.
=> Data formats icons change

content/data-visualization.md
Use a more recent link to the matplotlib parts of figure example
=> [ENH] update Link

content/catfacts.jsonl, content/web-apis.ipynb
Make an actual jsonlines file.
=> Fix jsonlines example

content/dependencies.rst
=> add :: to get code formatting of the one-liners

content/binder.rst
- Only minor fixes, no content changes
=> content/binder: Misc updates

content/packaging.rst
- Minor updates, mostly to small formatting
- Also update to keypoints
=> content/packaging: Minor updates

content/dependencies.rst
=> content/dependencies: Minor updates from my read-though

content/scripts.rst
- Mostly minor, automerge after some time
=> content/scripts: Some suggestions for clarity

content/dependencies.rst
This PR updates the dependencies chapter for 2023.
Updated package versions and did small modifications to the text.
=> Updated dependencies chapter for 2023 course

content/pandas.rst
- Closes: #135 (convert column back to years)
- Various other minor clarity changes, for example:
- typo fixing
- more explanation
- add some `df` to show how we see values as we work.
- etc.
- All code verified to work.
- Review: probably can be automerge
=> content/pandas: Basic revision, no major changes.

content/index.rst, content/productivity.rst, resources/code/productivity/code_style_example.py, resources/code/productivity/exercise1.py, resources/code/productivity/exercise1_solution.py, resources/code/productivity/exercise2.py, resources/code/productivity/exercise2_solution.py, resources/code/productivity/lint_example.py, software/environment-conda-forge.yml
This PR adds a new chapter on productivity tools such as linters and code formatters.
=> content/productivity: Adding a chapter on productivity tools

content/pandas.rst
- csv already added in previous commit (so that this can be tested)
=> content/pandas: Adjust lesson to use local copy of laureates.csv

content/dependencies.rst
- Reduce the time of the first exercise.  For only a discussion, 15
minutes is way to long.  Make it 5 minutes.
=> content/dependencies: Reduce exercise 1 time (it's just discussion)

content/index.rst
Link to YouTube playlist also needs an update.
=> Update link to course page from index

software/environment.yml
We need this for the xarray lecture. It contains the sample dataset.
=> add pythia_datasets to environment.yml

content/packaging.rst
=> Fix remaining typos from the packaging episode
