AaltoSciComp/python-for-scicomp

conf.py
requirements.txt

- I found that sphinx_rtd_theme didn't meet accessibility guidelines
for color contrast, so I made this package to work on it by
overriding some CSS:
https://github.com/AaltoSciComp/sphinx_rtd_theme_ext_color_contrast
- This isn't the work of a designer, I just increased saturation of
some colors to hack around the problem.
- Advantage is this probably makes it better for presentations and
teaching - less eye strain.
- Review: does the preview make sense?  Maybe we shouldn't merge right
before a lesson...

Adjust color contrast to sphinx_rtd_theme

---

conf.py
index.rst
parallel.rst

- Basic outline of parallel episode, from #98
- Enable the builtin "todo" directive.  By default it doesn't appear
in the output but can be configured to do so.
- Review: minimial, simple copy from the issue as a template to fill
in, and will be revised later.

Template of parallel episode

---

numpy.rst

- Remove matrix class metions, closes #67
- Instead, comment about how array math is implemented and link to
some other functions.
- Review: general check

numpy: remove mentions of the matrix class, add other refs

---

.github/workflows/sphinx.yml

- Don't save all gh-pages histotry
- This is a PR, but since PRs also deploy, it is probably a null
operation and will immediately come into effect anyway... there may
sill be a better way though.
- I originally thought it was safer, now seems reliable enough it's
not needed.  I wish we could keep just the last 5 commits or
something, though...
- Review: is there any need for gh-pages history?

.github/workflows/sphinx: force_orphan = True

---

parallel.rst

- Describe dask, task queues, and workflow managers (new).
- Dask example, link to queues, mention Snakemake
- No examples of task queues or Snakemake, but point out it is for
embarrasingly parallel work and may be redundant if you have a
cluster schedule.
- Review: is this minimally good for tomorrow?  I don't think we
should spend more time on it.
- Alternatively I'm thinking to skip task queues + workflow
managers, and we can mention just dask (or remove the whole
section) since this will take a while anyway.  But I think that
mentioning but say we have no examples will entertain some people
and make them realize these things are available.

parallel: Add initial dask/task queue description

---

content/pandas.rst

- Error in choosing passengers with the name "Margaret" : "Name" is used to index the df, while the current version assumes it is a column
- In example on melting data, the undefined variable `df` has been corrected to `runners`
- Incorrect column name: Survival --> Survived

Minor typos in examples

---

content/numpy.rst

- The first question at the start of the lesson what "What is vectorization?" and the term "vectorization" did not appear anywhere in the text. I moved the question down and updated the text to name-drop vectorization so that the question is actually answered.
- Introduced the `@` symbol for matrix multiplication. I think this is way more intuitive than `np.dot` and is supported as of python 3.5, so it's early "new" anymore.
- Added `.T` / `np.transpose` to the list of basic math operations. Thought it belonged there.
- Changed a type annotation from `bool` to `'bool'` to maintain consistency: NumPy types are now always given as strings. This is the more flexible approach, as it is straightforward to distinguish between `int8` and `int64` if you need it.

Some tweaks to the NumPy lesson

---

content/pandas.rst

Suggested additions:
- small discussion on python function call overheads. Code example provided is about 2x as fast as lru_cache for large fib(n) 
calls.
- pandas.eval() for large dataframe manipulations give some additional speed. Example gives about 2x speed.
https://jakevdp.github.io/PythonDataScienceHandbook/03.12-performance-eval-and-query.html
- small discussion on numpys int bottleneck
I also recommend some example on Numba. Sometimes it brings a significant speed up on functions when adding a simple decorator on top of a function
https://numba.pydata.org/

pandas.eval() for large dataframes, cpython function call overhead, np.int vs int

---

content/dependencies.rst

This PR adds more information on the mamba-side of conda ecosystem:
- Reorganize the conda-ecosystem box to have a more natural order:
-  Anaconda vs Miniconda
- conda vs mamba
- Anaconda Cloud vs conda-forge
- Link to mamba at the end
- Link to miniforge and mambaforge at the end

content/dependencies: Add more information about mamba-side of conda

---

content/numpy-advanced.rst

to get rid of "SyntaxError: invalid syntax"

add ',' on line 366

---

content/pandas.rst

"Name" is used as index so it could not be used in the example, I replaced it with another column name. There was a repetition of the same set command and I removed it.

fixing one error + one repetition

---

content/pandas.rst

Assuming that the indexing is still by key "Name", then the use of `titanic.loc` wants the key to slice. Another solution is to reindex by passenger ID, but then the loc and iloc solutions would look identical...

Fixing exercise 1 solution

---

content/dependencies.rst

one-liners were not  formatted, now two separate lines -->  copy-pasting the " into terminal on mac and wsl bash becomes wrong ", changed to ' to work

formatting one-liners in BASH and exchanging " with '

---

content/packaging.rst

fix code emphasis which fixes a build warning

---

content/jupyter.ipynb

- Related: #64 (makes it slightly bettter but not fully fixing)
- Introduce %%timeit as first magic since %%bash doesn't work on all
OSs.
- Not yet removing %%bash, I'd like to add another magic as an extra
example to not make it just about %%timeit
- I think that %%prun is most likely option for another demo but it
should have a longer example that gives a meaningful profile.

content/jupyter: Use timeit as first cell magic example

---

content/scripts.rst

- Makes this consistent with the actual script + the rest of the code.

content/scripts: Fix example, `output` isn't a optional argument

---

content/profiling.md

Hi @bast,
This is a very rough structure for the profiling lecture, I will refine the structure when I have time this week. Is the proposed structure OK so far?
There are two sections of the lecture with 20 minutes each and 2 exercises left to do. Should each of us work on one part of the lecture and one exercise? If yes, would you prefer to summarize the "productivity tools" lecture or do the introduction of the "profiling" part?

Add structure of profiling lecture

---

content/dependencies.rst

This PR contains major changes to the dependencies-page.
- More info on conda ecosystem
- Focus is on creating environments
- No more manual installation instructions, use environments instead
- Split conda environments and virtual environments into separate tabs throughout the doc for clarity of instructions

dependencies: Major changes all around

---

software/environment.yml

vega_datasets contains example datasets which are used in the Vega-Altair gallery of examples
having this dependency would make this exercise
easier: https://aaltoscicomp.github.io/python-for-scicomp/plotting-vega-altair/#exercise-adapting-a-gallery-example

adding vega_datasets to list of dependencies

---

content/xarray.rst

Add note for installation of missing packages in xarray lecture

---

Makefile
content/packaging.rst

- Add sphinx-autobuild make livehtml rule
- Test PyPI API token and virtual environment instructions
- By the power of grayskull!
This is important because of two things
1. Username and password authentication does not work in PyPI or Test PyPI anymore. 2FA is mandatory.
2. conda-skeleton does not work with modern Python packages which do not use setup.py
3. grayskull is recommended and it works
I have tested the commands and fixed it.
cc: @rkdarst

Fix packaging episode

---

content/libraries.rst

This PR updates some of the listed libraries.

libraries: Update some of the listed packages

---

content/packaging-example-project/test.py
content/packaging-example-project/test_editable.py
content/packaging.rst

- Encourage editable install in exercise 1
- Link to choosealicense and pyOpenSci tutorial
- Note on how to specify dependencies from github

Packaging: pip install editable and pyproject dependencies and license

---

content/xarray.rst
software/environment.yml

Fix #295 
Instead of inventing values for stock prices and trading volumes, the data is now downloaded via the `yfinance` package.

Update exercise 2 in xarray lecture 
